### ISSUE TITLE
When will you complete it??

### ISSUE THREAD

**Issue by Tushargupta9800** [Tokenyet/AndroidMediaQuery#1]
hey bud, I'm a newbee flutter developer and i'm trying to make a music player and for that i need a plugin to load all the songs from my device. Can you plz tell me until when your plugin will be ready or u can tell me any other plugin for that as i see u hvn't work on this plugin for 5 months straight.

# plz help

**Comment by Tokenyet** [comment]
No plan for cleanup the code, but you could check the example for knowing how to use It. For me, the other plugin(project) use another method that so lag, so I create the plugin on this purpose.
